version: '3'

services:
  php:
    build: ./env/php
    container_name: php_pipeline
    volumes:
      - ./src:/var/www/html/

  apache:
    build: ./env/apache
    container_name: apache_pipeline
    depends_on:
      - php
    ports:
      - 7560:80
    volumes:
      # Mounting your app on the volume
      - ./src/:/var/www/html/
