<?php


namespace Domain\Pipelines;


use Lib\Pipeline\PipelineStep;

class GenerateDelivery extends PipelineStep
{
    public function validate()
    {

    }

    public function execute()
    {
        return parent::execute(); // TODO: Change the autogenerated stub
    }
}